// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqa0DIXsAuZ8cEMUOrrYh5gJQlsSZkdY',
    appId: '1:876251392098:web:1e9cefede522349154893b',
    messagingSenderId: '876251392098',
    projectId: 'backendtesis',
    authDomain: 'backendtesis.firebaseapp.com',
    storageBucket: 'backendtesis.firebasestorage.app',
    measurementId: 'G-D9FFC0RFEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2Zqu8SjFRwUlBWMDdVcL56y0_thZ4vo',
    appId: '1:876251392098:android:e25fe3988ee40f4554893b',
    messagingSenderId: '876251392098',
    projectId: 'backendtesis',
    storageBucket: 'backendtesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1q8DBfn5GOly1QfxN0lQO0QjKpdjgfg',
    appId: '1:876251392098:ios:0437fb748b4673f654893b',
    messagingSenderId: '876251392098',
    projectId: 'backendtesis',
    storageBucket: 'backendtesis.firebasestorage.app',
    iosBundleId: 'com.example.appAcademicaOffline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1q8DBfn5GOly1QfxN0lQO0QjKpdjgfg',
    appId: '1:876251392098:ios:0437fb748b4673f654893b',
    messagingSenderId: '876251392098',
    projectId: 'backendtesis',
    storageBucket: 'backendtesis.firebasestorage.app',
    iosBundleId: 'com.example.appAcademicaOffline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyqa0DIXsAuZ8cEMUOrrYh5gJQlsSZkdY',
    appId: '1:876251392098:web:254f7503dae3c95854893b',
    messagingSenderId: '876251392098',
    projectId: 'backendtesis',
    authDomain: 'backendtesis.firebaseapp.com',
    storageBucket: 'backendtesis.firebasestorage.app',
    measurementId: 'G-K07Z1V9RHV',
  );

}